##---- Baseline MVSNet ---##
sync_bn: True

multiprocessing_distributed: True

# 1/2^i, i=0,1,2,3 for full,half,quarter,eighth scale, respectively;
#depth_map_scale_int: 0

# network
network_class_name: 'bl_itermvs'
network_sub_class_name: 'bl_itermvs_pose'
network_sub_class_name_str: 'bl_itermvsp'

#pretrain_mvsnet_path: ''
## No refine_network module
pretrain_itermvs_path: 'saved/pretrained/itermvs/dtu/model_000015.ckpt'
our_pretrain_itermvs_path: 'exp66B-ddp-bl_itermvs-Dil1inv-scanpz2-Z0.25to20-D32-epo5-LR1.25e-4-c-bs64-h256xw320-rtxA6ks3/ckpt_epoch_002.pth.tar'

# residual posenet module;
pretrain_residual_pose_path: 'exp71A-ddp-raftpsQr4G3pairspf-Dil1inv-scanpz2-Z0.25to20-D64-epo2-LR2.5e-5-c-bs40-h256xw256-rtxA6ks3/ckpt_epoch_001.pth.tar'
pretrain_atten_path: ''


#freeze_layers: 'encoder,depth' # only train pose modules;
freeze_layers: '' # train all modules;

# -- mvs plane sweeping setup -- #
depth_binning: 'inverse'
num_depth_bins: 32

#--- loss ---#
loss_type: 'L1-inv'

