##---- Baseline IterMVS ---##
sync_bn: True

multiprocessing_distributed: True
#multiprocessing_distributed: False
#gpu_id: -1

# 1/2^i, i=0,1,2,3 for full,half,quarter,eighth scale, respectively;
depth_map_scale_int: 2 

# network
network_class_name: 'bl_itermvs'

pretrain_itermvs_path: 'saved/pretrained/itermvs/dtu/model_000015.ckpt'
our_pretrain_itermvs_path: ''
pretrain_residual_pose_path: ''
pretrain_atten_path: ''


# -- mvs plane sweeping setup -- #
depth_binning: 'inverse'
num_depth_bins: 32

#--- save result (for each image) or not ---#
#save_all_results: True
save_all_results: False

#--- loss ---#
loss_type: 'L1'