##---- Baseline MVSNet ---##

#--- DDP or DP related args ---#
multiprocessing_distributed: False

# 1/2^i, i=0,1,2,3 for full,half,quarter,eighth scale, respectively;
depth_map_scale_int: 2 

# network
network_class_name: 'bl_mvsnet'
network_sub_class_name: 'bl_mvsnet_pose_eval'
network_sub_class_name_str: 'bl_mvsnetp'

pretrain_mvsnet_path: ''
our_pretrain_mvsnet_path: ''
pretrain_residual_pose_path: ''
pretrain_atten_path: ''

# -- mvs plane sweeping setup -- #
depth_binning: 'linear'
#num_depth_bins: 192
num_depth_bins: 64
#num_depth_bins: 256 # original mvsnet by Yaoyao

#--- save result (for each image) or not ---#
#save_all_results: True
save_all_results: False

